---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rconway-flux-deployments
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/rconway/flux-deployments
