#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

trap "cd '${ORIG_DIR}'" EXIT

if test -n "$1"; then
  CONTEXT="--context=$1"
fi

watch kubectl $CONTEXT get ns,GitRepositories,HelmRepositories,Kustomizations,HelmReleases,svc,ingress -A
