#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

trap "cd '${ORIG_DIR}'" EXIT

watch kubectl get ns,GitRepositories,HelmRepositories,Kustomizations,HelmReleases,svc,ingress -A
