apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cheese
spec:
  chart:
    spec:
      chart: ./charts/cheese
      sourceRef:
        kind: GitRepository
        name: self
  values:
    baseHostname: 127.0.0.1.nip.io
  interval: 1m0s
