apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.2.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: repos
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: infra
  values:
    installCRDs: true
