apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: testing
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./components/testing
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client